loglevel: info
cpus: 1
monitoring:
  port: 5555
ssl:
   cert: "./certs/server.cert"
   key: "./certs/server.key"
protocols:
  http:
    enable: true
    mocks_dir: "./mocks"
    port: 8080
  https:
    enable: false
    port: 8443
  http2:
    enable: false
    port: 8081
  ws:
    enable: false
    mocks_dir: "./ws_mocks"
    port: 8082
  grpc:
    enable: false
    host: localhost
    port: 4312
    mocks_dir: "./grpc/mocks"
    protos_dir: "./grpc/protos"
backup:
  enable: true
  cron: "0 * * * *" # Hourly Backup
cache:
  enable: false
  ttl_seconds: 300
injection:
  enable: true
# ext_helpers: "./custom_handlebar.json" # Remove if not needed
origins:
  - http://localhost:3000/
  - http://localhost:3001/
  - http://localhost:5000/